server:
  port: 8083
database:
  driver: mysql
  # driver: sqlite
  host: 192.168.3.60
  port: 53306
  user: root
  password: "123456"
  name: ai_agent_go

# ingest:
#   enabled: true
#   fetch_interval_sec: 300
#   http_timeout_sec: 15
#   fetch_workers: 1
#   parser_grpc_addr: 127.0.0.1:50051
#   parser_grpc_insecure: true
#   parser_grpc_timeout_sec: 8
#   parser_dispatch_batch_size: 100
#   parser_callback_secret: ""

tenant:
  # default_tenant_id: "default"
  # default_tenant_name: "Default Tenant"
  # default_tenant_description: "This is the default tenant."
  # api_key_prefix: "sk-"
  # 16、24 或 32
  aes_key: "xxxxxxxxxxxxx"